const BLOCK_CARRIER_ENTITY_TYPE_ID = "sable:block_carrier";
const CARRIER_SEAT_COUNT = 512;
const BLOCK_CARRIER_CAPACITY = CARRIER_SEAT_COUNT - 1;
const BLOCK_SLOTS_PER_ENTITY = 2;
export {
  BLOCK_CARRIER_CAPACITY,
  BLOCK_CARRIER_ENTITY_TYPE_ID,
  BLOCK_SLOTS_PER_ENTITY,
  CARRIER_SEAT_COUNT
};
